spring:
  application:
    name: gateway-api-server

server:
  port: 8765
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
zuul:
  routes:
    limit-application:
      service-id: limit-application
  host:
    connect-timeout-millis: 30000
    
ribbon:
  eureka:
    enabled: false   